### ISSUE TITLE
create showtime scraper

### ISSUE THREAD

**Issue by stevenpollack** [stevenpollack/dairy_queen#1]
Check out [http://berlin.angloinfo.com/whatson/movies/0-0/All-titles/in-berlin/this-week](http://berlin.angloinfo.com/whatson/movies/0-0/All-titles/in-berlin/this-week); in particular, _Berlin-Tiergarten - CineStar - Original Sony Center_...

**Comment by ghost** [comment]
Done:

http://www.kimonolabs.com/api/ondemand/9q0fwoh2
