### ISSUE TITLE
API

### ISSUE THREAD

**Issue by franciscolourenco** [stevenpollack/dairy_queen#4]
https://dairy-queen.herokuapp.com/

Accepts post request with form-data.
Defaults:

```
    ads_mins = 15
    trailers_mins = 15
    max_waiting_mins = 45
    acceptable_overlap_mins = 0
    movies_to_exclude = 'Spectre, Star Wars' #set to None to disable
    interesting_movies = None # set to None to disable
    all_interesting_movies_must_be_in_dip = False # consider any dip that has at least one of the interesting mov
```

**Comment by stevenpollack** [comment]
Shit, I had no idea you had `dairy-queen.herokuapp.com`, can you share permissions with me to that, and I'll use that domain to host the app?

**Comment by franciscolourenco** [comment]
I just changed the name of the app, so I guess you can now use the domain. The code was just a quick prototype, I guess it is not useful anymore.
