### ISSUE TITLE
Need header "Access-Control-Allow-Origin" added to herokuapp

### ISSUE THREAD

**Issue by gabericharde** [stevenpollack/dairy_queen#9]
Receiving the following "XHMTLrequest cannot load" warning when trying to request/"GET" a double dip calculation from the herokuapp:

![screen shot 2016-03-26 at 9 42 43 pm](https://cloud.githubusercontent.com/assets/4109307/14062342/ba209866-f39b-11e5-8460-c2f5eb600117.png)

I guess you need to include this header in the response in order for AJAX to work?

**Comment by stevenpollack** [comment]
that's weird, I'm having no issues performing this GET request... Try using `https://...`?

**Comment by franciscolourenco** [comment]
@stevenpollack are you using the command line? This is a security feature implemented by the browser.

**Comment by stevenpollack** [comment]
Shit, I am. How do I enable this?

**Comment by franciscolourenco** [comment]
Something like the first snippet should do the trick http://stackoverflow.com/a/25860353/1445812

**Comment by stevenpollack** [comment]
Right on, try it now @gabericharde and let me know.

**Comment by gabericharde** [comment]
Still getting the same error as above when hitting `https://double-dipper.herokuapp.com/double-dips?...` and when hitting `https://locache.herokuapp.com/double-dips?...` only getting a 404 code.

**Comment by stevenpollack** [comment]
1. The new URL for dairy queen is https://dairy-queen.herokuapp.com
2. That locache end point (resource) doesn't exist... I think you want root
   (ie. locache.herokuapp.com/?location=...)

**Comment by gabericharde** [comment]
Requests are taking awhile, but it seems to be working with `https://dairy-queen.herokuapp.com/double-dips...` Thanks again buddy!
